### ISSUE TITLE
Missing sensor for Volume Level

### ISSUE THREAD

**Issue by Headkillah** [samuelspagl/ha_samsung_soundbar#8] opened 2023-12-13 07:04 UTC
First, BIG THX for the integration. Your´s one the only that works with my Soundbar Q995B :)

But the question i have is:

I´m able to change the volume, but there´s only a slider. Is it possible that you can build in a sensor for the volume level like in the official SmartThings Integration (sensor.soundbar_volume)?

That would be fantastic :)

**Comment by samuelspagl** [comment] 2023-12-14 18:54
@Headkillah Happy to hear that :) Thanks a lot!

I can add a sensor sure. I'll try to do it tomorrow.

**Comment by samuelspagl** [comment] 2023-12-14 19:46
@Headkillah I added a sensor. If you want to (and know how to) you can first try the MR and tell me if its implemented as intended.

**Comment by Headkillah** [comment] 2023-12-15 22:00
> @Headkillah I added a sensor. If you want to (and know how to) you can first try the MR and tell me if its implemented as intended.

Hey :) Sorry for late answer I'm a litle bit busy ... Will test it this weekend, I promise:)

**Comment by Headkillah** [comment] 2023-12-23 20:30
Sensor is present, but the value is not quite correct or is apparently calculated differently. For example: In the SmartThings integration, the volume level is displayed as 6%, but your integration shows me a volume level of 20. If I now set it to 7%, for example, the level in your integration is 23.333333333 :D And unfortunately the sensor is not updated immediately, there is a time delay of approx. 10 seconds.

**Comment by samuelspagl** [comment] 2023-12-24 08:45
@Headkillah Yeah I saw your comment in the PR, but didn't get to it yet, sorry, the christmas stress is kicking 😄 

So the 10 seconds delay is something I probably can't change, I'll take a look at it again, but homeassistant has some constants for the refresh time of each entity type. For the "MediaPlayer" it is 10 seconds. And I can't change that value, at least as far as I know of.

The wrong value is probably because I forgot converting the units 😄 

I'll try to do it as fast as I can.

**Comment by samuelspagl** [comment] 2024-01-02 20:19
@Headkillah I just committed a new version. It really was just a minor change, sorry for taking so long. I tested in on my instance and it is now displaying the same value as reported in the Smart Things App.

That is what you wished for correct?

**Closed** 2024-01-08 10:27 UTC
