### ISSUE TITLE
Sound mode selection and eq preset lists disappeeared

### ISSUE THREAD

**Issue by letrouf** [samuelspagl/ha_samsung_soundbar#29] opened 2024-04-03 12:33 UTC
Hi, first of all thank you for this integration that is perfect for my daily use.
Since a couple of weeks the list inside the sound mode preset entity and eq present entity are empty. The rest of the integration works as expected though. I tried to reinstall with new smartthings token but same issue persist.
Any thoughts ?
![Capture d'écran 2024-04-03 141713](https://github.com/samuelspagl/ha_samsung_soundbar/assets/146136707/2d0a4ed0-40b3-4e43-8136-e70c9e8b4273)
John

**Comment by samuelspagl** [comment] 2024-04-03 14:19
Hi John (@letrouf),

Yeah, the problem lies at Samsung. Quite a few have this issue currently. It seems that Samsung either broke or intentionally changed something regarding the SmartThingsAPI.
Like you mentioned most of the things work, but the "update" process of the "extra capabilities" like EQ, Woofer, Soundmodes, Advanced Audio (Bassmode, Nightmode, VoiceEnhancer) is broken. You will also see quite a few logged error messages ^^.
It is still possible to send commands to adjust all of the values, but the retrieval of the status for these extra capabilities is broken. 

#26 is a long yet very detailed thread about the issue.
I already wrote Samsung in 3 different locations and hope to get some answers 🤷🏻‍♂️. Lets see...

For now I released a new Alpha Version that can enable/disable the entities for the extra capabilities and also stop the update process. I will add some services in the next days (when I have some free time) to still send commands to the soundbar.

I would close this issue if thats fine with you, as it is basically a duplicate of #26.

Best Samuel ✌️

**Closed** 2024-04-03 14:59 UTC
