### ISSUE TITLE
[BUG] - Failed to set up

### ISSUE THREAD

**Issue by smoldersonline** [samuelspagl/ha_samsung_soundbar#41] opened 2024-10-07 10:09 UTC
Thank you very much for sharing this integration!

Unfortunately it fails to set up my Q990D - see below.

Your support would be greatly appreciated.

Thanks again.

Logger: homeassistant.config_entries
Source: config_entries.py:594 
First occurred: 11:18:34 (4 occurrences) 
Last logged: 12:00:31

Error setting up entry samsung_soundbar for samsung_soundbar
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 594, in async_setup
    result = await component.async_setup_entry(hass, self)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/samsung_soundbar/__init__.py", line 69, in async_setup_entry
    await soundbar_device.update()
  File "/config/custom_components/samsung_soundbar/api_extension/SoundbarDevice.py", line 63, in update
    await self._update_media()
  File "/config/custom_components/samsung_soundbar/api_extension/SoundbarDevice.py", line 75, in _update_media
    self.__media_artist = self.device.status._attributes["audioTrackData"].value[
                          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: 'NoneType' object is not subscriptable

**Comment by samuelspagl** [comment] 2024-10-07 12:31
This is a duplicate of #39.
Please take a look at this issue.

**Closed as not planned by samuelspagl** 2024-10-07 12:31 UTC
