### ISSUE TITLE
Failed to set up

### ISSUE THREAD

**Issue by traqnski89** [samuelspagl/ha_samsung_soundbar#27] opened 2024-04-01 13:42 UTC
Hello,
I have a Q800A soundbar and till 2 days ago everything was working fine.
Unfortunately I have changed my router and I needed to reset the soundbar and configured again.
Since than I am not able to connect it back to HA.
I tried to delete the integration, to generate a new token, I have reset and reconfigured the sound bar again!
Nothing helps! I receive always the same error!
![image](https://github.com/samuelspagl/ha_samsung_soundbar/assets/115040099/7bd4948b-9707-4dac-85c2-5572f877e16d)

![image](https://github.com/samuelspagl/ha_samsung_soundbar/assets/115040099/06db69cf-0025-4742-bfaf-ab0f253ccb36)

**Comment by samuelspagl** [comment] 2024-04-01 15:56
Hi @traqnski89,

Yeah I know, so this is the same as #26, it seems that Samsung changed something in their API, which is really unfortunate. 

I am already thinking about how to tackle this.

**Comment by samuelspagl** [comment] 2024-04-02 05:07
I would close this issue as it is a duplicate of #26.
Feel free to join the discussion there.

I released a new Alpha version yesterday evening, that lets you enable / disable the entities and also the update process for certain capabilities.
At the current stage, retrieving the status of **all** of those extra capabilities is not working. The linked thread explains things in more detail.

I am thinking about adding services for those extra capabilities, as it is still possible to set values there. 

Pull Request: https://github.com/samuelspagl/ha_samsung_soundbar/pull/28
https://github.com/samuelspagl/ha_samsung_soundbar/releases/tag/0.4.0b1

If there is anything else, feel free to reopen.

**Closed by samuelspagl** 2024-04-02 05:07 UTC
