### ISSUE TITLE
Setting up Q995 not possible - 'NoneType' object is not subscriptable

### ISSUE THREAD

**Issue by hudecitydave** [samuelspagl/ha_samsung_soundbar#40] opened 2024-08-11 16:15 UTC
Whatever I do, I run in this error on latest HA and version 0.4.0:

Logger: homeassistant.config_entries
Quelle: config_entries.py:604
Erstmals aufgetreten: 14:34:28 (8 Vorkommnisse)
Zuletzt protokolliert: 17:58:32

Error setting up entry samsung_soundbar for samsung_soundbar
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 604, in async_setup
    result = await component.async_setup_entry(hass, self)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/samsung_soundbar/__init__.py", line 69, in async_setup_entry
    await soundbar_device.update()
  File "/config/custom_components/samsung_soundbar/api_extension/SoundbarDevice.py", line 63, in update
    await self._update_media()
  File "/config/custom_components/samsung_soundbar/api_extension/SoundbarDevice.py", line 75, in _update_media
    self.__media_artist = self.device.status._attributes["audioTrackData"].value[
                          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: 'NoneType' object is not subscriptable

**Comment by samuelspagl** [comment] 2024-08-22 15:47
Hi there ✌️,
Sorry for the late response, my timetable was quite full the last few weeks.
This is a duplicate of #39, therefore I would close this and answer in the other thread.

**Closed as completed by samuelspagl** 2024-08-22 15:47 UTC
